export interface CaseFileMeta {
  slug: string
  title: string
  subtitle: string
  classificationCode: string
  department: string
  threatLevel: 'LOW' | 'MODERATE' | 'CRITICAL' | 'TERMINAL'
  tags: string[]
}

export const CASE_FILES: CaseFileMeta[] = [
  {
    slug: 'endless-talker',
    title: 'OPERATION: DEAD AIR',
    subtitle: 'Surviving the Infinite Talker',
    classificationCode: 'NSA-7742-ORAL',
    department: 'Dept. of Conversational Threat Assessment',
    threatLevel: 'CRITICAL',
    tags: ['social survival', 'field manual', 'extraction protocols'],
  },
  {
    slug: 'gcds',
    title: 'Disease Classification Bulletin No. 41',
    subtitle: 'Geriatric Comedic Delusion Syndrome',
    classificationCode: 'NICP-41-GCDS',
    department: 'Dept. of Intergenerational Humor Trauma',
    threatLevel: 'TERMINAL',
    tags: ['clinical', 'dad jokes', 'facility placement'],
  },
  {
    slug: 'boring-class-survival-guide',
    title: 'The Boring Class Survival Manual',
    subtitle: 'Surviving an Excruciatingly Boring Class',
    classificationCode: 'DAE-3RD-ED',
    department: 'Dept. of Academic Endurance',
    threatLevel: 'CRITICAL',
    tags: ['academic survival', 'field manual', 'mental escape'],
  },
  {
    slug: 'cndd',
    title: 'Curriculum Compliance Audit No. 41',
    subtitle: 'Chronic Narrative Divergence Disorder in Active Teaching Personnel',
    classificationCode: 'OCINC/UBD-2026/0041',
    department: 'Office of Curricular Integrity & Narrative Containment',
    threatLevel: 'TERMINAL',
    tags: ['clinical', 'academic', 'biographical containment'],
  },
  {
    slug: 'public-audio-advisory',
    title: 'Advisory Notice PCA-0047-AUD',
    subtitle: 'Public Disturbance: Unsolicited Audio Broadcast in a Shared Space',
    classificationCode: 'PCA-0047-AUD',
    department: 'Public Conduct Authority',
    threatLevel: 'MODERATE',
    tags: ['public conduct', 'audio hazard', 'headphone noncompliance'],
  },
  {
    slug: 'non-functional-instructor',
    title: 'Emergency Academic Field Card',
    subtitle: 'Issued to Students Enrolled Under a Non-Functional Instructor',
    classificationCode: 'EAF-CARD-NF1',
    department: 'Dept. of Academic Endurance',
    threatLevel: 'CRITICAL',
    tags: ['academic survival', 'field card', 'instructor noncompliance'],
  },
  {
    slug: 'the-vision',
    title: 'INCIDENT REPORT: THE CROC SIGHTING',
    subtitle: 'A Witnessed Beauty. A Revoked Assessment. A Case Closed.',
    classificationCode: 'DVA-009-FTW',
    department: 'Dept. of Romantic Threat Assessment',
    threatLevel: 'LOW',
    tags: ['field incident', 'assessment revoked', 'footwear'],
  },
  {
    slug: 'courtesy-call',
    title: 'A COURTESY CALL',
    subtitle: 'In Which a Young Professional Makes a House Call, and Both Parties Conduct Themselves With Great Dignity',
    classificationCode: 'OCR-1A-CIVIL',
    department: 'Dept. of Professional Conduct & Etiquette',
    threatLevel: 'TERMINAL',
    tags: ['one-act play', 'client relations', 'sanitised tools'],
  },
  {
    slug: 'death-enterprise',
    title: 'DEATH ENTERPRISE',
    subtitle: 'A Once in a Lifetime Experience. We Are Very Precise About That Wording.',
    classificationCode: 'DE-EST-INF',
    department: 'Dept. of Eternal & Irrevocable Services',
    threatLevel: 'TERMINAL',
    tags: ['hospitality', 'spa services', 'zero negative reviews'],
  },
  {
    slug: 'writing-guide',
    title: 'KEYS TO EFFECTIVE WRITING',
    subtitle: 'Five Principles for Serious Writers, and One Final Disclosure',
    classificationCode: 'LIT-5K-ED1',
    department: 'Dept. of Literary Instruction & Controlled Demolition',
    threatLevel: 'CRITICAL',
    tags: ['writing', 'self-help', 'fraud confirmed'],
  },
  {
    slug: 'trial-transcript',
    title: 'THE STATE v. DEFENDANT [REDACTED]',
    subtitle: 'Organ Trafficking Charge Arising From Voluntary Acceptance of a Human Heart',
    classificationCode: 'HC/2024/0091-T47',
    department: 'Dept. of Romantic Jurisprudence',
    threatLevel: 'TERMINAL',
    tags: ['court transcript', 'organ trafficking', 'evidence speaks for itself'],
  },
  {
    slug: 'rug-ad',
    title: 'THE RUG. FINALLY.',
    subtitle: 'Everything You Never Knew You Did Not Want. Limited Supply. Extremely Limited Desire To Keep Them.',
    classificationCode: 'COMM-RUG-001',
    department: 'Dept. of Involuntary Commerce & Product Disposal',
    threatLevel: 'MODERATE',
    tags: ['product advertisement', 'highly flammable', 'seller in distress'],
  },
  {
    slug: 'the-noise-outside',
    title: 'THE NOISE OUTSIDE',
    subtitle: 'Three Groups. One Window. A Minister Who Has Thoughts About Civilization.',
    classificationCode: 'MR-XII-4-FIC',
    department: 'Dept. of Political Satire & Civilized Animals',
    threatLevel: 'TERMINAL',
    tags: ['short fiction', 'political satire', 'severe irony'],
  },
  {
    slug: 'botanical-sin',
    title: 'BOTANICAL SIN',
    subtitle: 'A Philosophical Broadside on the Ethics of Eating',
    classificationCode: 'PB-ETH-001',
    department: 'Dept. of Moral Ecology & Dietary Jurisprudence',
    threatLevel: 'MODERATE',
    tags: ['satirical verse', 'philosophy', 'food ethics'],
  },
  {
    slug: 'butt-cradler',
    title: 'BUTT CRADLER 2,000',
    subtitle: 'A State of the Art Device Designed to Hug, Hold, and Fully Commit to Your Tushy Tush Tush.',
    classificationCode: 'COMM-BC-2000',
    department: 'Dept. of Involuntary Commerce & Product Disposal',
    threatLevel: 'MODERATE',
    tags: ['product advertisement', 'seating apparatus', 'special configuration available'],
  },
  {
    slug: 'i-met-death-last-night',
    title: 'I MET DEATH LAST NIGHT',
    subtitle: 'A Dream Narrative. First Person. One Night. She Was Breathtaking.',
    classificationCode: 'MR-DN-001',
    department: 'Dept. of Nocturnal Incident Documentation',
    threatLevel: 'CRITICAL',
    tags: ['dream narrative', 'personal account', 'she had a scythe'],
  },
]